name: Test secret variables workflow
on:
  workflow_dispatch:


jobs:
  secret_variables_job:
    runs-on: ubuntu-latest
    steps:
    - name: Get the secret value
      run: echo "The secret value is ${{ secrets.MY_SECRET_KEY }}"
